import 'package:movie_database/models/movie_model.dart';

final  movies = [
  Movie(id: 1, name: 'Avengers', category: 'Action/Sci-Fi', releaseYear: 2012, rating: 8.2, image: 'avengers.jpg',),
  Movie(id: 2, name: 'Captain America', category: 'Action/Sci-Fi', releaseYear: 2011, rating: 8.3, image: 'captainamerica.jpg'),
  Movie(id: 3, name: 'Captain Marvel', category: 'Action/Sci-Fi', releaseYear: 2018, rating: 8.7, image: 'captainmarvel.jpg'),
  Movie(id: 4, name: 'Dr Strange', category: 'Action/Sci-Fi', releaseYear: 2017, rating: 7.5, image: 'drstrange.jpg'),
  Movie(id: 5, name: 'Iron Man', category: 'Action/Sci-Fi', releaseYear: 2008, rating: 8.4, image: 'ironman.jpg'),
  Movie(id: 6, name: 'Spider Man : Homecoming', category: 'Action/Sci-Fi', releaseYear: 2016, rating: 8.1, image: 'spiderman.jpeg'),
  Movie(id: 7, name: 'Thor', category: 'Action/Sci-Fi', releaseYear: 2009, rating: 8.0, image: 'thor.jpg'),
];

final description = ''' Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla vitae felis gravida, feugiat purus a, ullamcorper quam. Etiam auctor placerat purus quis ultricies. Curabitur ipsum dolor, bibendum quis nisi eu, egestas tincidunt velit. Phasellus blandit nulla at metus tempus pellentesque. Ut ornare nisi sed elit tincidunt imperdiet. Praesent id dolor in lorem auctor facilisis. Maecenas consectetur iaculis felis, ut interdum magna condimentum quis. Vivamus id dignissim nisi. Duis et pretium mi, eget sollicitudin sapien. Nulla facilisi.

Mauris vel libero rutrum, ultricies nibh egetLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla vitae felis gravida, feugiat purus a, ullamcorper quam. Etiam auctor placerat purus quis ultricies. Curabitur ipsum dolor, bibendum quis nisi eu, egestas tincidunt velit. Phasellus blandit nulla at metus tempus pellentesque. Ut ornare nisi sed elit tincidunt imperdiet. Praesent id dolor in lorem auctor facilisis. Maecenas consectetur iaculis felis, ut interdum magna condimentum quis. Vivamus id dignissim nisi. Duis et pretium mi, eget sollicitudin sapien. Nulla facilisi.

Mauris vel libero rutrum, ultricies nibh egetLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla vitae felis gravida, feugiat purus a, ullamcorper quam. Etiam auctor placerat purus quis ultricies. Curabitur ipsum dolor, bibendum quis nisi eu, egestas tincidunt velit. Phasellus blandit nulla at metus tempus pellentesque. Ut ornare nisi sed elit tincidunt imperdiet. Praesent id dolor in lorem auctor facilisis. Maecenas consectetur iaculis felis, ut interdum magna condimentum quis. Vivamus id dignissim nisi. Duis et pretium mi, eget sollicitudin sapien. Nulla facilisi.

Mauris vel libero rutrum, ultricies nibh egetLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla vitae felis gravida, feugiat purus a, ullamcorper quam. Etiam auctor placerat purus quis ultricies. Curabitur ipsum dolor, bibendum quis nisi eu, egestas tincidunt velit. Phasellus blandit nulla at metus tempus pellentesque. Ut ornare nisi sed elit tincidunt imperdiet. Praesent id dolor in lorem auctor facilisis. Maecenas consectetur iaculis felis, ut interdum magna condimentum quis. Vivamus id dignissim nisi. Duis et pretium mi, eget sollicitudin sapien. Nulla facilisi.

Mauris vel libero rutrum, ultricies nibh egetLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla vitae felis gravida, feugiat purus a, ullamcorper quam. Etiam auctor placerat purus quis ultricies. Curabitur ipsum dolor, bibendum quis nisi eu, egestas tincidunt velit. Phasellus blandit nulla at metus tempus pellentesque. Ut ornare nisi sed elit tincidunt imperdiet. Praesent id dolor in lorem auctor facilisis. Maecenas consectetur iaculis felis, ut interdum magna condimentum quis. Vivamus id dignissim nisi. Duis et pretium mi, eget sollicitudin sapien. Nulla facilisi.

Mauris vel libero rutrum, ultricies nibh egetLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla vitae felis gravida, feugiat purus a, ullamcorper quam. Etiam auctor placerat purus quis ultricies. Curabitur ipsum dolor, bibendum quis nisi eu, egestas tincidunt velit. Phasellus blandit nulla at metus tempus pellentesque. Ut ornare nisi sed elit tincidunt imperdiet. Praesent id dolor in lorem auctor facilisis. Maecenas consectetur iaculis felis, ut interdum magna condimentum quis. Vivamus id dignissim nisi. Duis et pretium mi, eget sollicitudin sapien. Nulla facilisi.

Mauris vel libero rutrum, ultricies nibh egetLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla vitae felis gravida, feugiat purus a, ullamcorper quam. Etiam auctor placerat purus quis ultricies. Curabitur ipsum dolor, bibendum quis nisi eu, egestas tincidunt velit. Phasellus blandit nulla at metus tempus pellentesque. Ut ornare nisi sed elit tincidunt imperdiet. Praesent id dolor in lorem auctor facilisis. Maecenas consectetur iaculis felis, ut interdum magna condimentum quis. Vivamus id dignissim nisi. Duis et pretium mi, eget sollicitudin sapien. Nulla facilisi.

Mauris vel libero rutrum, ultricies nibh egetLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla vitae felis gravida, feugiat purus a, ullamcorper quam. Etiam auctor placerat purus quis ultricies. Curabitur ipsum dolor, bibendum quis nisi eu, egestas tincidunt velit. Phasellus blandit nulla at metus tempus pellentesque. Ut ornare nisi sed elit tincidunt imperdiet. Praesent id dolor in lorem auctor facilisis. Maecenas consectetur iaculis felis, ut interdum magna condimentum quis. Vivamus id dignissim nisi. Duis et pretium mi, eget sollicitudin sapien. Nulla facilisi.

Mauris vel libero rutrum, ultricies nibh egetLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla vitae felis gravida, feugiat purus a, ullamcorper quam. Etiam auctor placerat purus quis ultricies. Curabitur ipsum dolor, bibendum quis nisi eu, egestas tincidunt velit. Phasellus blandit nulla at metus tempus pellentesque. Ut ornare nisi sed elit tincidunt imperdiet. Praesent id dolor in lorem auctor facilisis. Maecenas consectetur iaculis felis, ut interdum magna condimentum quis. Vivamus id dignissim nisi. Duis et pretium mi, eget sollicitudin sapien. Nulla facilisi.

Mauris vel libero rutrum, ultricies nibh egetLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla vitae felis gravida, feugiat purus a, ullamcorper quam. Etiam auctor placerat purus quis ultricies. Curabitur ipsum dolor, bibendum quis nisi eu, egestas tincidunt velit. Phasellus blandit nulla at metus tempus pellentesque. Ut ornare nisi sed elit tincidunt imperdiet. Praesent id dolor in lorem auctor facilisis. Maecenas consectetur iaculis felis, ut interdum magna condimentum quis. Vivamus id dignissim nisi. Duis et pretium mi, eget sollicitudin sapien. Nulla facilisi.

Mauris vel libero rutrum, ultricies nibh egetLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla vitae felis gravida, feugiat purus a, ullamcorper quam. Etiam auctor placerat purus quis ultricies. Curabitur ipsum dolor, bibendum quis nisi eu, egestas tincidunt velit. Phasellus blandit nulla at metus tempus pellentesque. Ut ornare nisi sed elit tincidunt imperdiet. Praesent id dolor in lorem auctor facilisis. Maecenas consectetur iaculis felis, ut interdum magna condimentum quis. Vivamus id dignissim nisi. Duis et pretium mi, eget sollicitudin sapien. Nulla facilisi.

Mauris vel libero rutrum, ultricies nibh egetLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla vitae felis gravida, feugiat purus a, ullamcorper quam. Etiam auctor placerat purus quis ultricies. Curabitur ipsum dolor, bibendum quis nisi eu, egestas tincidunt velit. Phasellus blandit nulla at metus tempus pellentesque. Ut ornare nisi sed elit tincidunt imperdiet. Praesent id dolor in lorem auctor facilisis. Maecenas consectetur iaculis felis, ut interdum magna condimentum quis. Vivamus id dignissim nisi. Duis et pretium mi, eget sollicitudin sapien. Nulla facilisi.

Mauris vel libero rutrum, ultricies nibh egetLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla vitae felis gravida, feugiat purus a, ullamcorper quam. Etiam auctor placerat purus quis ultricies. Curabitur ipsum dolor, bibendum quis nisi eu, egestas tincidunt velit. Phasellus blandit nulla at metus tempus pellentesque. Ut ornare nisi sed elit tincidunt imperdiet. Praesent id dolor in lorem auctor facilisis. Maecenas consectetur iaculis felis, ut interdum magna condimentum quis. Vivamus id dignissim nisi. Duis et pretium mi, eget sollicitudin sapien. Nulla facilisi.

Mauris vel libero rutrum, ultricies nibh egetLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla vitae felis gravida, feugiat purus a, ullamcorper quam. Etiam auctor placerat purus quis ultricies. Curabitur ipsum dolor, bibendum quis nisi eu, egestas tincidunt velit. Phasellus blandit nulla at metus tempus pellentesque. Ut ornare nisi sed elit tincidunt imperdiet. Praesent id dolor in lorem auctor facilisis. Maecenas consectetur iaculis felis, ut interdum magna condimentum quis. Vivamus id dignissim nisi. Duis et pretium mi, eget sollicitudin sapien. Nulla facilisi.

Mauris vel libero rutrum, ultricies nibh egetLorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla vitae felis gravida, feugiat purus a, ullamcorper quam. Etiam auctor placerat purus quis ultricies. Curabitur ipsum dolor, bibendum quis nisi eu, egestas tincidunt velit. Phasellus blandit nulla at metus tempus pellentesque. Ut ornare nisi sed elit tincidunt imperdiet. Praesent id dolor in lorem auctor facilisis. Maecenas consectetur iaculis felis, ut interdum magna condimentum quis. Vivamus id dignissim nisi. Duis et pretium mi, eget sollicitudin sapien. Nulla facilisi.

Mauris vel libero rutrum, ultricies nibh eget, maximus odio. Suspendisse tincidunt blandit augue, vitae mattis ante hendrerit quis. Duis quis tincidunt lectus, et feugiat magna. Nunc luctus pulvinar enim a venenatis. Phasellus hendrerit nisl sed sollicitudin elementum. Fusce pulvinar, diam vel tempor venenatis, felis dolor dictum ligula, ut rhoncus ex lorem eu ante. In porttitor vitae leo sit amet dapibus. Nulla vel laoreet elit. Morbi laoreet sem et scelerisque ornare. Etiam rhoncus, urna ac cursus rhoncus, diam lectus porttitor massa, tincidunt suscipit odio ante eleifend tortor. Aenean non massa ac mauris dapibus facilisis. Sed sollicitudin congue turpis vitae fringilla. ''';